name: migu
on: 
  schedule: 
    - cron: 56 20 * * *
  workflow_dispatch:
jobs:
  main:
    name: Fetch And Modify
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    - name: fetch source 
      run: |
          wget https://smart.pendy.dpdns.org/m3u/merged_judy.m3u -O raw.m3u
          python extract.py --input raw.m3u --output op.m3u --keyword '咪咕视频'
          python deduplicate.py -i op.m3u -o migu.m3u
          ls -al
    - name: CommitAndPush
      run: |
        git clone https://github.com/ioptu/t2mjdwkjndw3.git
        cd t2mjdwkjndw3 && git init
        mv ../migu.m3u ./migu.m3u
        git config --global user.email "github@github.com"
        git config --global user.name "Github Actions"
        git add .
        git commit -m "Build By Github Actions"
        git remote set-url origin https://${{ secrets.TOKEN }}@github.com/ioptu/t2mjdwkjndw3.git
        git push -u origin main
