name: quwangtong
on: 
  schedule: 
    - cron: 56 10 * * *
  workflow_dispatch:
jobs:
  main:
    name: Fetch And Modify
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    - name: fetch source 
      run: |
          wget https://github.com/suxuang/myIPTV/raw/refs/heads/main/ipv4.m3u -O raw.m3u
          python extract.py --input raw.m3u --output op.m3u --keyword 'group-title="全网通"'
          python deduplicate.py -i op.m3u -o qwt.m3u
          ls -al
    - name: CommitAndPush
      run: |
        git clone https://github.com/ioptu/t2mjdwkjndw3.git
        cd t2mjdwkjndw3 && git init
        mv ../qwt.m3u ./qwt.m3u
        git config --global user.email "github@github.com"
        git config --global user.name "Github Actions"
        git add .
        git commit -m "Build By Github Actions"
        git remote set-url origin https://${{ secrets.TOKEN }}@github.com/ioptu/t2mjdwkjndw3.git
        git push -u origin main
