name: qwt-finurl
on: 
#  schedule: 
#    - cron: 30 * * * *
  workflow_dispatch:
jobs:
  main:
    name: Modify
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许推送代码
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    - name: fetch source 
      run: |
          pip install requests 
          #pip install tqdm
          python ./scripts/rdfinurl.py --input qwt.m3u --output fuqwt.m3u --retries 2
          ls -al
          #cat errors.log
    - name: CommitAndPush
      run: |
        # 获取仓库名称（${VAR#*/} 是 Bash 的字符串操作，去掉 owner/ 前缀）
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        git config --global user.email "github@github.com"
        git config --global user.name "Github Actions"
        
        # 克隆仓库（使用 HTTPS + TOKEN 避免权限问题）
        git clone "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        cd "$REPO_NAME" || exit 1  # 强制失败时退出

        # 后续操作...
        mv ../fuqwt.m3u ./fuqwt.m3u
        git add .
        git commit -m "Update: $(date +'%Y-%m-%d %H:%M:%S')"
        git push origin main
