name: txt2m3u
on: 
  schedule: 
    - cron: 00 05 * * *
  workflow_dispatch:
jobs:
  main:
    name: Fetch And Convert
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许推送代码
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    - name: fetch source 
      run: |
          # wget https://github.com/zwc456baby/iptv_alive/raw/master/live.txt -O input.txt
          wget https://gitee.com/xxy002/zhiboyuan/raw/master/dsy -O input.txt
          node ./scripts/txt2m3u.js -i input.txt -o output.m3u
          ls -al
    - name: CommitAndPush
      run: |
        # 获取仓库名称（${VAR#*/} 是 Bash 的字符串操作，去掉 owner/ 前缀）
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        git config --global user.email "github@github.com"
        git config --global user.name "Github Actions"
        
        # 克隆仓库（使用 HTTPS + TOKEN 避免权限问题）
        git clone "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        cd "$REPO_NAME" || exit 1  # 强制失败时退出

        # 后续操作...
        mv ../output.m3u ./t2m_output.m3u
        git add .
        git commit -m "Update: $(date +'%Y-%m-%d %H:%M:%S')"
        git push origin main
